### PR TITLE
Minor documentation fixes in german macro.cnc 

### PR DESCRIPTION
**Pull request by Schallbert**
- add EdingCNC OEM parameters and description
- refine some message dialogs
- fix typo

### CODE REVIEW

**Comment by dkern** [comment]
Hello @Schallbert !

First of all, thank you very much for your work. I will fix the typos and review the english version too, just to not have different messages/comments in both files.

But you really can't change `DlgMsg "Spinogy_Error"` to return a message. The `Spinogy_Error` stand for the image `dialogPictures/Spinogy_Error.png`, wich will be displayed in this case. You disabled it by changing the message.

So I will do the changes in both files and close your PR. Thanks!

**Comment by dkern** [comment]
So, I've fixed the typo only. Eding only supports limited chars on message. So the message in line #111 was already too long. Even before your change. So I ended up cutting the message even more. Not perfect, but otherwise the end of the message gets cut off.

Also, I didn't include OEM parameters to the header, because they are documented in the manual. Otherwise you would also need to address M and G commands. And that's too much. ;)

Thanks again!

**Comment by Schallbert** [comment]
Hi @dkern 
that's totally fine with me. I learned that [this DlgMsg](https://github.com/spinogy/edingcnc-macros/blob/c549716e2f2c90a50edbbc6941bbdbfac82a8cbf/german/spinogy_macro.cnc#L60)  just was supposed to show the asset which is fine to me, but would suggest a comment similar to my proposal in the macro file to clarify the intention.

Also agree to not add OEM parameters for the reasons you provided. 
Will delete my branch.

**Comment by dkern** [comment]
I think the intentions is clarified by the `if` before the dialog what also has a description comment. But I've added comments to all dialogs that uses images now, as you suggested. Just that everybody knows why the message looks a bit strange. ;)

I didn't make it a new version now, but it's in the main branch.

**Comment by Schallbert** [comment]
Looks good to me now, and thanks for the quick turnaround.
Cheers,
_Schallbert_

**Pull request closed without merging**
